receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'spring-boot-app'
          scrape_interval: 5s
          static_configs:
            - targets: ['spring-boot-app:8080']
          metrics_path: "/actuator/prometheus"

exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"  # Push metrics to Prometheus

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite]